name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    strategy:
      matrix:
        # Currently building x86_64 only for fast CI (~4 mins).
        # To enable ARM builds, add aarch64 back: [x86_64, aarch64]
        arch: [x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install deps
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          # Use the static binaries because it's unable to use a package manager 
          curl https://download.docker.com/linux/static/stable/x86_64/docker-26.0.0.tgz --output ./docker.tgz
          tar xzvf docker.tgz
          mv docker/* /usr/bin
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: CineHDR.flatpak
          manifest-path: build-aux/flatpak/io.github.rusmikev.CineHDR.json
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: false
          arch: ${{ matrix.arch }}
